# Generated by Django 4.2.5 on 2024-01-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('model', models.CharField(max_length=100, verbose_name='Product model')),
                ('release_date', models.DateField(verbose_name='Release date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Debt to the supplier')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='network.element')),
            ],
            options={
                'verbose_name': 'Network element',
                'verbose_name_plural': 'Network elements',
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Contact email')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('building_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Building number')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.element', verbose_name='Network element')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
